version: '3.8'
services:
  mysql:
    image: mysql:8.0.35
    env_file:
      - ./env/mysql.env
    volumes:
#      - /Users/repoleved/Desktop/docker/sdf-mysql:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
#  eureka:
#    build: 
#      context: ./recon-discovery-service
#      dockerfile: Dockerfile
#    env_file:
#      - env/recon-eureka.env
#    ports:
#      - $RECON_EUREKA_HOST_PORT:$RECON_EUREKA_APP_PORT
  sdf-core:
    build:
      context: ./Space-Defense-Force
      dockerfile: Dockerfile
    env_file:
      - ./env/sdf-core.env
    ports:
      - $SDF_CORE_HOST_PORT:$SDF_CORE_APP_PORT
    depends_on:
#      - eureka
      - mysql
#  recon-reports:
#    build:
#      context: ./recon-report-service
#      dockerfile: Dockerfile
#    env_file:
#      - ./env/recon-report.env
#    ports:
#      - $RECON_REPORT_HOST_PORT:$RECON_REPORT_APP_PORT
#    depends_on:
#      - eureka
#      - mysql
#  recon-email:
#    build:
#      context: ./recon-email-service
#      dockerfile: Dockerfile
#    env_file:
#      - env/recon-email.env
#    ports:
#      - $RECON_EMAIL_HOST_PORT:$RECON_EMAIL_APP_PORT
#    depends_on:
#      - eureka
#      - mysql
